#:schema node_modules/wrangler/config-schema.json
name = "app-publish"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[r2_buckets]]
binding = "appBucket"
bucket_name = "app-publish"
